basePath: /v1
definitions:
  jwt.TokenParames:
    properties:
      mobile:
        description: 手机号
        type: string
      name:
        description: 姓名
        type: string
      uid:
        description: uid
        type: integer
    type: object
  model.CheckinRecord:
    properties:
      created_at:
        type: string
      created_by:
        type: integer
      customer_id:
        description: 签到人ID
        type: integer
      day:
        description: 签到第几天
        type: integer
      help_checkin_customer_id:
        description: 帮签人ID
        type: integer
      id:
        type: integer
      status:
        type: string
      updated_at:
        type: string
      updated_by:
        type: integer
    type: object
  model.Customer:
    properties:
      created_at:
        type: string
      created_by:
        type: integer
      id:
        type: integer
      last_checkin_time:
        description: 最后一次签到时间
        type: string
      mobile:
        description: 手机号
        type: string
      name:
        description: 称呼
        type: string
      status:
        type: string
      updated_at:
        type: string
      updated_by:
        type: integer
    type: object
  model.IssueRecord:
    properties:
      created_at:
        type: string
      created_by:
        type: integer
      customer_id:
        description: 顾客ID
        type: integer
      id:
        type: integer
      merchant_id:
        description: 店铺ID
        type: integer
      received:
        description: 在对应店铺已兑换的礼品数
        type: integer
      status:
        type: string
      total_receive:
        description: 在对应店铺可领取的总礼品数
        type: integer
      updated_at:
        type: string
      updated_by:
        type: integer
    type: object
  model.Merchant:
    properties:
      address:
        description: 地址
        type: string
      catering_type:
        description: 餐饮类型
        type: string
      checkin_days:
        description: 签到天数多少天可领取礼品
        type: integer
      checkin_num:
        description: 达到指定签到天数后，可领取的礼品数量
        type: integer
      contact_name:
        description: 联系人
        type: string
      contact_phone:
        description: 联系人电话
        type: string
      created_at:
        type: string
      created_by:
        type: integer
      id:
        type: integer
      lat:
        description: 纬度
        type: number
      lon:
        description: 经度
        type: number
      poster:
        description: 商户海报
        type: string
      received:
        description: 已领礼品数量
        type: integer
      status:
        type: string
      store_avatar:
        description: 店铺头像
        type: string
      store_name:
        description: 店名
        type: string
      total_receive:
        description: 该店礼品一共可领取总数
        type: integer
      updated_at:
        type: string
      updated_by:
        type: integer
    type: object
  model.MerchantLoginVO:
    properties:
      code:
        example: 验证码
        type: string
      contact_phone:
        example: 手机号
        type: string
    required:
    - code
    - contact_phone
    type: object
  model.MerchantVO:
    properties:
      address:
        description: 地址
        type: string
      catering_type:
        description: 餐饮类型
        type: string
      checkin_days:
        description: 签到天数多少天可领取礼品
        type: integer
      checkin_num:
        description: 达到指定签到天数后，可领取的礼品数量
        type: integer
      contact_name:
        description: 联系人
        type: string
      contact_phone:
        description: 联系人电话
        type: string
      lat:
        description: 纬度
        type: number
      lon:
        description: 经度
        type: number
      poster:
        description: 商户海报
        type: string
      received:
        description: 已领礼品数量
        type: integer
      store_avatar:
        description: 店铺头像
        type: string
      store_name:
        description: 店名
        type: string
      total_receive:
        description: 该店礼品一共可领取总数
        type: integer
    required:
    - address
    - contact_phone
    - lat
    - lon
    - store_avatar
    - store_name
    - total_receive
    type: object
  model.MerchantWriteOffRespVO:
    properties:
      customer:
        $ref: '#/definitions/model.Customer'
        type: object
      issue_record:
        $ref: '#/definitions/model.IssueRecord'
        type: object
      merchant:
        $ref: '#/definitions/model.Merchant'
        type: object
    type: object
  server.BaseResponse:
    properties:
      code:
        type: string
      data:
        type: object
      error:
        type: string
      message:
        type: string
      status:
        type: boolean
    type: object
  server.CheckinRecordResponse:
    properties:
      code:
        description: 业务状态码
        type: string
      data:
        items:
          $ref: '#/definitions/model.CheckinRecord'
        type: array
      error:
        description: Error信息
        type: string
      message:
        description: 提示消息
        type: string
      status:
        description: 状态
        type: boolean
    type: object
  server.CodeResponse:
    properties:
      code:
        description: 业务状态码
        type: string
      error:
        description: Error信息
        type: string
      message:
        description: 提示消息
        type: string
      status:
        description: 状态
        type: boolean
    type: object
  server.CustomerDetailResponse:
    properties:
      code:
        description: 业务状态码
        type: string
      data:
        $ref: '#/definitions/model.Customer'
        type: object
      error:
        description: Error信息
        type: string
      message:
        description: 提示消息
        type: string
      status:
        description: 状态
        type: boolean
    type: object
  server.CustomerListResponse:
    properties:
      code:
        description: 业务状态码
        type: string
      data:
        items:
          $ref: '#/definitions/model.Customer'
        type: array
      error:
        description: Error信息
        type: string
      message:
        description: 提示消息
        type: string
      status:
        description: 状态
        type: boolean
    type: object
  server.ExecWriteOffRequest:
    properties:
      tokenParames:
        $ref: '#/definitions/jwt.TokenParames'
        type: object
    type: object
  server.ExecWriteOffResponse:
    properties:
      code:
        description: 业务状态码
        type: string
      data:
        $ref: '#/definitions/model.MerchantWriteOffRespVO'
        type: object
      error:
        description: Error信息
        type: string
      message:
        description: 提示消息
        type: string
      status:
        description: 状态
        type: boolean
    type: object
  server.MerchantAddResponse:
    properties:
      code:
        description: 业务状态码
        type: string
      error:
        description: Error信息
        type: string
      message:
        description: 提示消息
        type: string
      status:
        description: 状态
        type: boolean
    type: object
  server.MerchantDetailResponse:
    properties:
      code:
        description: 业务状态码
        type: string
      data:
        $ref: '#/definitions/model.Merchant'
        type: object
      error:
        description: Error信息
        type: string
      message:
        description: 提示消息
        type: string
      status:
        description: 状态
        type: boolean
    type: object
  server.MerchantListResponse:
    properties:
      code:
        description: 业务状态码
        type: string
      data:
        items:
          $ref: '#/definitions/model.Merchant'
        type: array
      error:
        description: Error信息
        type: string
      message:
        description: 提示消息
        type: string
      status:
        description: 状态
        type: boolean
    type: object
  server.MerchantLoginResponse:
    properties:
      code:
        description: 业务状态码
        type: string
      data:
        description: access token
        type: string
      error:
        description: Error信息
        type: string
      message:
        description: 提示消息
        type: string
      status:
        description: 状态
        type: boolean
    type: object
  server.UserLoginRequest:
    properties:
      name:
        description: 用户名
        type: string
      password:
        description: 密码
        type: string
    required:
    - name
    - password
    type: object
  server.UserLoginResponse:
    properties:
      code:
        description: 业务状态码
        type: string
      data:
        description: access token
        type: string
      error:
        description: Error信息
        type: string
      message:
        description: 提示消息
        type: string
      status:
        description: 状态
        type: boolean
    type: object
  server.WriteOffResponse:
    properties:
      code:
        description: 业务状态码
        type: string
      data:
        $ref: '#/definitions/model.MerchantWriteOffRespVO'
        type: object
      error:
        description: Error信息
        type: string
      message:
        description: 提示消息
        type: string
      status:
        description: 状态
        type: boolean
    type: object
info:
  contact: {}
  description: 福利签API文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: 福利签API文档
  version: "1.0"
paths:
  /customers:
    get:
      consumes:
      - application/json
      description: get customer list
      parameters:
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 联系电话
        in: query
        name: mobile
        type: string
      - default: 1
        description: 页码
        in: query
        name: page_no
        type: integer
      - default: 10
        description: 页数
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":true}'
          schema:
            $ref: '#/definitions/server.CustomerListResponse'
      security:
      - ApiKeyAuth: []
      summary: 获取客户列表
      tags:
      - 客户
  /customers/checkin_record:
    get:
      consumes:
      - application/json
      description: get customer checkin record
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":true}'
          schema:
            $ref: '#/definitions/server.CheckinRecordResponse'
      security:
      - ApiKeyAuth: []
      summary: 获取签到记录
      tags:
      - 客户
  /customers/detail:
    get:
      consumes:
      - application/json
      description: get customer detail
      parameters:
      - description: 客户ID,客户访问时可不传
        in: query
        name: customer_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":true}'
          schema:
            $ref: '#/definitions/server.CustomerDetailResponse'
      security:
      - ApiKeyAuth: []
      summary: 获取客户详情
      tags:
      - 客户
  /files/download:
    get:
      consumes:
      - application/json
      description: download file
      parameters:
      - description: filename
        in: query
        name: filename
        required: true
        type: string
      - default: '"avatar", "poster"'
        description: file type
        in: query
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":true}'
          schema:
            $ref: '#/definitions/server.BaseResponse'
      summary: 下载文件
      tags:
      - 文件
  /files/upload:
    post:
      consumes:
      - multipart/form-data
      description: upload file
      parameters:
      - description: upload file
        in: formData
        name: file
        required: true
        type: file
      - default: '"avatar", "poster"'
        description: file type
        in: query
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":true}'
          schema:
            $ref: '#/definitions/server.BaseResponse'
      summary: 上传文件
      tags:
      - 文件
  /merchants:
    get:
      consumes:
      - application/json
      description: get merchant list
      parameters:
      - description: 商户名
        in: query
        name: store_name
        type: string
      - description: 联系人
        in: query
        name: contact_name
        type: string
      - description: 联系电话
        in: query
        name: contact_phone
        type: string
      - default: 1
        description: 页码
        in: query
        name: page_no
        type: integer
      - default: 10
        description: 页数
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":true}'
          schema:
            $ref: '#/definitions/server.MerchantListResponse'
      security:
      - ApiKeyAuth: []
      summary: 获取商户列表
      tags:
      - 商户
    post:
      consumes:
      - application/json
      description: create new merchant
      parameters:
      - description: 参数
        in: body
        name: args
        required: true
        schema:
          $ref: '#/definitions/model.MerchantVO'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":true}'
          schema:
            $ref: '#/definitions/server.MerchantAddResponse'
      security:
      - ApiKeyAuth: []
      summary: 新增商户
      tags:
      - 商户
  /merchants/detail:
    get:
      consumes:
      - application/json
      description: get merchant detail
      parameters:
      - description: 商户ID,商户访问时可不传
        in: query
        name: merchant_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":true}'
          schema:
            $ref: '#/definitions/server.MerchantDetailResponse'
      security:
      - ApiKeyAuth: []
      summary: 获取商户详情信息
      tags:
      - 商户
  /merchants/login:
    post:
      consumes:
      - application/json
      description: merchant login
      parameters:
      - description: 参数
        in: body
        name: args
        required: true
        schema:
          $ref: '#/definitions/model.MerchantLoginVO'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":true}'
          schema:
            $ref: '#/definitions/server.MerchantLoginResponse'
      summary: 商户登录
      tags:
      - 商户
  /merchants/writeoff:
    get:
      consumes:
      - application/json
      description: merchant get customer write off
      parameters:
      - description: 客户ID
        in: query
        name: customer_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":true}'
          schema:
            $ref: '#/definitions/server.WriteOffResponse'
      security:
      - ApiKeyAuth: []
      summary: 商户获取核销信息
      tags:
      - 商户
    post:
      consumes:
      - application/json
      description: merchant exec write off
      parameters:
      - description: 参数
        in: body
        name: args
        required: true
        schema:
          $ref: '#/definitions/server.ExecWriteOffRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":true}'
          schema:
            $ref: '#/definitions/server.ExecWriteOffResponse'
      security:
      - ApiKeyAuth: []
      summary: 商户核销
      tags:
      - 商户
  /users/login:
    post:
      consumes:
      - application/json
      description: user login
      parameters:
      - description: 参数
        in: body
        name: args
        required: true
        schema:
          $ref: '#/definitions/server.UserLoginRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":true}'
          schema:
            $ref: '#/definitions/server.UserLoginResponse'
      summary: 后台用户登录
      tags:
      - 后台用户
  /verify_code:
    get:
      consumes:
      - application/json
      description: send sms code
      parameters:
      - description: 手机号
        in: query
        name: mobile
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":true}'
          schema:
            $ref: '#/definitions/server.CodeResponse'
      summary: 发送验证码
      tags:
      - 验证码
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
